name: GoCast

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and unit test
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Build
      run: make build

    - name: Install fpm
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm ruby ruby-dev
        sudo gem install fpm

    - name: Git repository status
      run: |
        echo $(git describe --tags $(git rev-list --tags --max-count=1))
        echo $(git describe --tags $(git rev-list --tags --max-count=1) | sed 's/^v//g')

    - name: Package
      run: make package-deb package-rpm

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*
        retention-days: 14
        
    - name: Test
      run: make test
